apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: componenta-devfile-sample-go-basic-private-devfile-nested-ksar
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tovk-tenant/mc-golang-nested/componenta-devfile-sample-go-basic-private-devfile-nested-ksar@sha256:f28e0294da5e15e24e752efd2c1f8d081d1cf346421245f801b2507cd076145c
        name: my-go
        resources: {}
status: {}
