apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: componentb-devfile-sample-go-basic-private-devfile-nested-nepl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: componentb-devfile-sample-go-basic-private-devfile-nested-nepl
    app.kubernetes.io/part-of: mc-golang-nested
  name: componentb-devfile-sample-go-basic-private-devfile-nested-nepl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: componentb-devfile-sample-go-basic-private-devfile-nested-nepl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: componentb-devfile-sample-go-basic-private-devfile-nested-nepl
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tovk-tenant/mc-golang-nested/componentb-devfile-sample-go-basic-private-devfile-nested-nepl@sha256:4d3d056710db853fd1927415f1cc1198472e70c3c4d5286626a5843e0e50c4bb
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
